#+TITLE:     Dotfiles
#+AUTHOR:    Jimmy Cozza
#+OPTIONS:   toc:2

* Basic Structure
** I use arch, btw
*** When I set up a new machine.  I usually just go with [[https://github.com/archlinux/archinstall][Archinstall]] or something like [[https://endeavouros.com/][EndeavourOS]].
*** I use [[https://awesomewm.org/][AwesomeWM]] as my everyday Window Manager.  I also have xfce installed just in case I break awesome beyond repair...it's nice to have a backup
*** The main setup script [[file:archSetup.sh][archSetup.sh]] is auto generated from the [[file:archSetup.org][the archSetup.org file]]
* Install from empty machine
** Make sure you have an ssh key generated and added to github if you care about that kind of thing
** =ssh-keygen -t ed25519 -C "email@email.com"=
** =git clone git@github.com:JimmyCozza/dotfiles.git=
** =cd dotfiles && ./archSetup.sh=
** enjoy
* Basics
** Neovim
*** Mostly converted to lua
*** Packer.nvim as my plugin manager
*** Built in LSP, still considering tinkering with DAP
** Doom Emacs
*** I can't seem to stop using [[https://orgmode.org/][org mode]] and [[https://magit.vc/][magit]], so I also have some basic config for when I use emacs as my daily driver.
** AwesomeWM
*** awesomewm-git is the better version for me.
** Rofi
*** Rofi is cool...but you know what's cooler?  This monstrosity that I stole from this dude (https://github.com/Vidianos-Giannitsis)
#+BEGIN_SRC emacs-lisp
(setq counsel-linux-app-format-function 'counsel-linux-app-format-function-name-pretty)
 (defun emacs-run-launcher ()
   "Create and select a frame called emacs-run-launcher which consists only of a minibuffer and has specific dimensions. Run counsel-linux-app on that frame, which is an emacs command that prompts you to select an app and open it in a dmenu like behaviour. Delete the frame after that command has exited"
   (interactive)
   (custom-set-variables
   '(ivy-fixed-height-minibuffer nil))
   (with-selected-frame (make-frame '((name . "emacs-run-launcher")
				       (minibuffer . only)
				       (width . 120)
				       (height . 11)))
     (unwind-protect
	  (counsel-linux-app)
	(delete-frame))))
#+END_SRC
*** I mean, I still use rofi because obviously it's great...but that emacs-run-launcher is pretty neat.  It puts me 1 step closer to committing to EXWM...
** Alacritty
*** Everything about my alacritty config is stock except for a couple things.
**** Colorthemes, Font, Size...
**** And the last 3 lines which intercept CTRL+D, CTRL+SHIFT+D, and CTRL+W and output commands to split tmux windows vertically, horizontally, or close window (respectively).  Why did I set up my alacritty this way?  Because I'm an idiot and now the muscle memory is built in and I haven't ever removed this.  Really sucks when you accidentally open a python repl and you try to exit it by hitting CTRL+D and instead of exiting you mash it 17 times and your terminal looks like it's wearing pinstripes
#+BEGIN_SRC yaml
  - { key: D,        mods: Control,        chars: "\x02\x25"                        }
  - { key: D,        mods: Control|Shift,  chars: "\x02\x22"                        }
  - { key: W,        mods: Control,        chars: "\x02\x78"                        }
#+END_SRC
**** Anyway, I should probably remove these and get those keybindings added to tmux some other way so I don't forget about these 3 bindings I added years ago
** Sxhkd
*** I'm still using a couple hotkeys that are keeping me with sxhkd, but I will probably switch everything over to awesomewm keybindings and remove this library completely.
** Picom
*** Really only using the compositor for a blur effect on the awesomewm clients
